---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

version: 1

name: base

description: "Personal Fedora Atomic image based on Universal Blue, Base image with no gui."

base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:

  - from-file: common/20-system.yml
  - from-file: common/30-apps.yml
  - from-file: common/80-cleanup.yml


  # -----------------------------------------------
  # Sign image
  # -----------------------------------------------

  - type: signing